// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGOgpSzv6Rv9GMaXmBZSJMM9T10xcVaKY',
    appId: '1:941444510026:web:ffe530557d3b5ee2f4d1b3',
    messagingSenderId: '941444510026',
    projectId: 'suitup-5bafb',
    authDomain: 'suitup-5bafb.firebaseapp.com',
    storageBucket: 'suitup-5bafb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiVzcTAHb7JSFCO9nTScYjqG19Vf-sTyE',
    appId: '1:941444510026:android:090859af216d798bf4d1b3',
    messagingSenderId: '941444510026',
    projectId: 'suitup-5bafb',
    storageBucket: 'suitup-5bafb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPR7MxRtSqltsB8gxrInWABnQ0Ypo2cEc',
    appId: '1:941444510026:ios:61225e4390f9d58df4d1b3',
    messagingSenderId: '941444510026',
    projectId: 'suitup-5bafb',
    storageBucket: 'suitup-5bafb.appspot.com',
    iosClientId: '941444510026-kqcmaelc7431cafvmoaup3opm2s5lp8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPR7MxRtSqltsB8gxrInWABnQ0Ypo2cEc',
    appId: '1:941444510026:ios:573b0016bc02632af4d1b3',
    messagingSenderId: '941444510026',
    projectId: 'suitup-5bafb',
    storageBucket: 'suitup-5bafb.appspot.com',
    iosClientId: '941444510026-sqcu4ck0ljb5te2qf0hgjukrg71vqn03.apps.googleusercontent.com',
    iosBundleId: 'com.example.coolapp.RunnerTests',
  );
}
